FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine as build
WORKDIR /src
RUN --mount=type=bind,source=blazorwdemo.csproj,target=blazorwdemo.csproj \
    --mount=type=cache,id=nuget,target=/root/.nuget/package \
    dotnet restore
COPY . .

EXPOSE 8080
EXPOSE 443
CMD [ "dotnet","watch" ,"--non-interactive" ]
