version: "3"
services:
  webapp:
    build: 
      context: ./webapp
      dockerfile: Dockerfile
      target: deploy
    image: webapp:prod
    container_name: webapp_prod_running
    expose:
      - 80
    ports:
      - "8000:80"