version: "3"
services:
  webapp:
    build: 
      context: ./webapp
      dockerfile: Dockerfile.prod
      target: deploy
    image: webapp:prod
    container_name: webapp_prod_running
    expose:
      - 8080
    ports:
      - "8099:8080"