FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine as build
WORKDIR /src
RUN --mount=type=bind,source=blazoruwebapp.csproj,target=blazoruwebapp.csproj \
    --mount=type=cache,id=nuget,target=/root/.nuget/package \
    dotnet restore
COPY . .
EXPOSE 8080
CMD [ "dotnet","watch" ,"--non-interactive", "--urls=http://*:8080" ]


FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine as development
WORKDIR /src
COPY . .
EXPOSE 8080
CMD [ "dotnet","run", "--no-launch-profile" ]
