FROM node:20-alpine as build
WORKDIR /src
RUN 
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm install -g npm@latest \
    npm ci
ENV NODE_ENV=Development
COPY . .
RUN ["npm", "run", "build"]
EXPOSE 80
CMD [ "npm","run","preview" ]