name: Publish Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

env:
  REGISTRY: kvruntime.io
  IMAGE_NAME: ${{ github.repository.name }}
  IMAGE_VERSION: 1.0.0


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          context: ./webapp
          file: Dockerfile.prod
        
      - name: Build and test
        uses: docker/build-push-action@v5
        
        with:
          file: ./webapp/Dockerfile
          target: build
          load: true

      - name: Build and push tagged version
        uses: docker/build-push-action@v5
        with:
          file: ./webapp/Dockerfile
          push: true
          target: deploy
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/webapp:${{ steps.meta.outputs.label }}
            ${{ secrets.DOCKER_USERNAME }}/webapp:latest
     
      - name: Trigger render deploy
        run: |
          echo "Start deployment"
          curl ${{ secrets.RENDER_DEPLOY_KEY }}


      
